export const DEFAULT_CHART_HEIGHT = 220;
export const DEFAULT_CHART_HORIZONTAL_INSET = 32;
export const DEFAULT_CHART_PADDING_TOP = 16;
export const DEFAULT_CHART_PLOT_AREA_RATIO = 0.75;
export const DEFAULT_CHART_SCROLL_PADDING_RIGHT = 24;
export const DEFAULT_CHART_Y_AXIS_WIDTH = 54;