export const COMMON_EXERCISES = [
  "Bench Press",
  "Squat",
  "Deadlift",
  "Overhead Press",
  "Barbell Row",
  "Pull Up",
  "Push Up",
  "Dumbbell Press",
  "Dumbbell Fly",
  "Incline Bench Press",
  "Lateral Raise",
  "Bicep Curl",
  "Tricep Extension",
  "Leg Press",
  "Leg Extension",
  "Leg Curl",
  "Calf Raise",
  "Lunges",
  "Plank",
  "Crunches",
  "Russian Twist",
  "Face Pull",
  "Lat Pulldown",
  "Seated Row",
  "Dips",
  "Hammer Curl",
  "Skullcrusher",
  "Front Squat",
  "Romanian Deadlift",
  "Bulgarian Split Squat",
  "Hip Thrust",
  "Mountain Climbers",
  "Burpees",
  "Box Jump",
  "Kettlebell Swing",
  "Clean and Jerk",
  "Snatch",
  "Arnold Press",
  "Preacher Curl",
  "Cable Crossover"
];
